@echo off
REM Launch Terminator after install-windows.bat has succeeded.
REM This file is also (re)generated by install-windows.ps1 with the correct
REM MSYS2 / Python paths baked in -- prefer the generated version if paths
REM differ on your machine.

set PATH=C:\msys64\mingw64\bin;%PATH%
cd /d "%~dp0"
C:\msys64\mingw64\bin\python3.exe terminator
pause
