'\" t
.\"     Title: terminator_config
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-04-22
.\"    Manual: Manual for Terminator
.\"    Source: Terminator
.\"  Language: English
.\"
.TH "TERMINATOR_CONFIG" "5" "2023-04-22" "Terminator" "Manual for Terminator"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
terminator_config \- the config file for Terminator terminal emulator
.SH "DESCRIPTION"
.sp
This file contains the configuration for \fBterminator\fP(1).
Terminator manages its configuration file via the ConfigObj library to
combine flexibility with clear, human editable files.
.br
Terminator offers a full GUI preferences editor which automatically
saves its config file so you don\(cqt need to write a config file by hand.
.SH "FILE LOCATION"
.sp
Normally the config file will be \fB~/.config/terminator/config\fP, but it
may be overridden with \fB$XDG_CONFIG_HOME\fP (in which case it will be
\fB$XDG_CONFIG_HOME/terminator/config\fP).
.SH "FILE FORMAT"
.sp
This is what a Terminator config file should look like:
.sp
.if n .RS 4
.nf
.fam C
# This is a comment
[global_config]
  focus = system

[keybindings]
  full_screen = <Ctrl><Shift>F11

[profiles]
  [[default]]
    font = Fixed 10
    background_color = "#000000" # A comment
    foreground_color = "#FFFFFF" # Note that hex colour values must be quoted
    scrollback_lines = \*(Aq500\*(Aq #More comment. Single quotes are valid too
    cursor_blink = True
    custom_command = "echo \(rs"foo#bar\(rs"" #Final comment \- this will work as expected.

[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0

[plugins]
.fam
.fi
.if n .RE
.SH "GLOBAL_CONFIG"
.sp
These are the options Terminator currently supports in the
\fBglobal_config\fP section.
.SS "Window Behavior & Appearance"
.sp
\fBwindow_state\fP = \fIstring\fP
.RS 4
Control how the Terminator window opens.
\*(Aqnormal\*(Aq to open normally.
\*(Aqmaximise\*(Aq to open in a maximised state.
\*(Aqfullscreen\*(Aq to open in a fullscreen state.
\*(Aqhidden\*(Aq to stay hidden.
.br
Default value: \fBnormal\fP
.RE
.sp
\fBalways_on_top\fP = \fIboolean\fP
.RS 4
If set to True, the window will always stay on top of other windows.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBsticky\fP = \fIboolean\fP
.RS 4
If set to True, the window will be visible on all workspaces.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBhide_on_lose_focus\fP = \fIboolean\fP
.RS 4
If set to True, the window will be hidden when focus is lost.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBhide_from_taskbar\fP = \fIboolean\fP
.RS 4
If set to True, the window will be hidden from the taskbar.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBgeometry_hinting\fP = \fIboolean\fP
.RS 4
If set to True, the window will resize in step with font sizes.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBsuppress_multiple_term_dialog\fP = \fIboolean\fP
.RS 4
If set to True, Terminator will ask for confirmation when closing
multiple terminals.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBborderless\fP = \fIboolean\fP
.RS 4
If set to True, the window will be started without window borders.
.br
Default value: \fBFalse\fP
.RE
.SS "Tab Behavior & Appearance"
.sp
\fBtab_position\fP = \fIstring\fP
.RS 4
Specify where tabs are placed.
Can be any of: \*(Aqtop\*(Aq, \*(Aqleft\*(Aq, \*(Aqright\*(Aq, \*(Aqbottom\*(Aq, \*(Aqhidden\*(Aq.
If set to \*(Aqhidden\*(Aq, the tab bar will not be shown. Hiding the tab is not
recommended, as it can be very confusing.
.br
Default value: \fBtop\fP
.RE
.sp
\fBclose_button_on_tab\fP = \fIboolean\fP
.RS 4
If set to True, tabs will have a close button on them.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBscroll_tabbar\fP = \fIboolean\fP
.RS 4
If set to True, the tab bar will not fill the width of the window.
The titlebars of the tabs will only take as much space as is necessary
for the text they contain. Except, that is, if the tabs no longer fit
the width of the window \- in that case scroll buttons will appear to
move through the tabs.
.br
Default value: \fBFalse\fP
.RE
.SS "Terminal Behavior & Appearance"
.sp
\fBfocus\fP = \fIstring\fP
.RS 4
Specify how focus is given to terminals.
\*(Aqclick\*(Aq means the focus only moves to a terminal after you click in it.
\*(Aqsloppy\*(Aq means the focus will follow the mouse pointer.
\*(Aqsystem\*(Aq means the focus will match that used by a GNOME window manager.
.br
Default value: \fBclick\fP
.RE
.sp
\fBalways_split_with_profile\fP = \fIboolean\fP
.RS 4
Specify whether splits/tabs will continue to use the profile of their
peer terminal. If set to False, they will always use the default profile.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBlink_single_click\fP = \fIboolean\fP
.RS 4
If set to True, clicking a link will open it even if \fBCtrl\fP is not
pressed.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBputty_paste_style\fP = \fIboolean\fP
.RS 4
If set to True, right\-click will paste text, while middle\-click will
popup the context menu. The source for the pasted text depends on the
value of \fBputty_paste_style_source_clipboard\fP.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBputty_paste_style_source_clipboard\fP = \fIboolean\fP
.RS 4
If set to True, the Clipboard will be used as source for pasting in
PuTTY style. Otherwise, the Primary Selection will be used.
.br
This option is ignored unless \fBputty_paste_style\fP is set to True.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBdisable_mouse_paste\fP = \fIboolean\fP
.RS 4
If set to True, mouse pasting will be disabled.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBsmart_copy\fP = \fIboolean\fP
.RS 4
If set to True, and there is no selection, the shortcut is allowed to
pass through. This is useful for overloading Ctrl\-C to copy a selection,
or send the SIGINT to the current process if there is no selection.
If False, the shortcut does not pass through at all, and the SIGINT does
not get sent.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBclear_select_on_copy\fP = \fIboolean\fP
.RS 4
If set to True, text selection will be cleared after copying using the
\fBcopy\fP keybinding.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBhandle_size\fP = \fIinteger\fP
.RS 4
Specify the width of the separator between terminals.
Anything outside the range 0\-20 (inclusive) will be ignored and the
default theme value will be used instead.
.br
Default value: \fB1\fP
.RE
.sp
\fBinactive_color_offset\fP = \fIfloat\fP
.RS 4
Specify how much to reduce the color values of fonts in terminals that
do not have focus.
.br
Default value: \fB0.8\fP
.RE
.sp
\fBinactive_bg_color_offset\fP = \fIfloat\fP
.RS 4
Specify how much to reduce the color values of the background in
terminals that do not have focus.
.br
Default value: \fB1.0\fP
.RE
.sp
\fBcell_width\fP = \fIfloat\fP
.RS 4
Specify the horizontal scale of character cells in the terminal.
.br
Default value: \fB1.0\fP
.RE
.sp
\fBcell_height\fP = \fIfloat\fP
.RS 4
Specify the vertical scale of character cells in the terminal.
.br
Default value: \fB1.0\fP
.RE
.sp
\fBtitle_at_bottom\fP = \fIboolean\fP
.RS 4
If set to True, the terminal\(cqs titlebar will be drawn at the bottom
instead of the top.
.br
Default value: \fBFalse\fP
.RE
.SS "Miscellaneous"
.sp
\fBdbus\fP = \fIboolean\fP
.RS 4
Specify whether Terminator will load its DBus server.
When this server is loaded, running Terminator multiple times will cause
the first Terminator process to open additional windows.
If this configuration item is set to False, or the python dbus module is
unavailable, running Terminator multiple times will run a separate
Terminator process for each invocation.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBextra_styling\fP = \fIboolean\fP
.RS 4
If set to True, Terminator may load an additional CSS styling file,
depending on the theme.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBbroadcast_default\fP = \fIstring\fP
.RS 4
Specify the default broadcast behavior.
Can be any of: \*(Aqall\*(Aq, \*(Aqgroup\*(Aq, \*(Aqoff\*(Aq.
.br
Default value: \fBgroup\fP
.RE
.sp
\fBuse_custom_url_handler\fP = \fIboolean\fP
.RS 4
If set to True, URL handling will be given over entirely to the program
specified by \*(Aqcustom_url_handler\*(Aq.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBcustom_url_handler\fP = \fIstring\fP
.RS 4
Specify the path to a program which accepts a URI as an argument and
does something relevant with it.
This option is ignored unless \fBuse_custom_url_handler\fP is set to True.
.RE
.sp
\fBcase_sensitive\fP = \fIboolean\fP
.RS 4
If set to True, uppercase and lowercase characters will be considered
different when searching text in the terminal.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBinvert_search\fP = \fIboolean\fP
.RS 4
If set to True, the search direction will be inverted (bottom to top)
when searching text in the terminal.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBenabled_plugins\fP = \fIlist of strings\fP
.RS 4
Specify which plugins will be loaded by default. All other plugin
classes will be ignored.
.br
Default value: \fB[\*(AqLaunchpadBugURLHandler\*(Aq, \*(AqLaunchpadCodeURLHandler\*(Aq, \*(AqAPTURLHandler\*(Aq]\fP
.RE
.SH "KEYBINDINGS"
.sp
These are the options Terminator currently supports in the \fBkeybindings\fP
section.
.SS "Creation & Destruction"
.sp
\fBsplit_horiz\fP
.RS 4
Split the current terminal horizontally.
.br
Default value: \fB<Ctrl><Shift>O\fP
.RE
.sp
\fBsplit_vert\fP
.RS 4
Split the current terminal vertically.
.br
Default value: \fB<Ctrl><Shift>E\fP
.RE
.sp
\fBsplit_auto\fP
.RS 4
Split the current terminal automatically, along the longer side.
.br
Default value: \fB<Ctrl><Shift>A\fP
.RE
.sp
\fBnew_tab\fP
.RS 4
Open a new tab.
.br
Default value: \fB<Ctrl><Shift>T\fP
.RE
.sp
\fBnew_window\fP
.RS 4
Open a new window as part of the existing process.
.br
Default value: \fB<Ctrl><Shift>I\fP
.RE
.sp
\fBnew_terminator\fP
.RS 4
Spawn a new Terminator process.
.br
Default value: \fB<Super>I\fP
.RE
.sp
\fBlayout_launcher\fP
.RS 4
Open the layout launcher.
.br
Default value: \fB<Alt>L\fP
.RE
.sp
\fBclose_term\fP
.RS 4
Close the current terminal.
.br
Default value: \fB<Ctrl><Shift>W\fP
.RE
.sp
\fBclose_window\fP
.RS 4
Close the current window.
.br
Default value: \fB<Ctrl><Shift>Q\fP
.RE
.SS "Navigation"
.sp
\fBcycle_next\fP
.RS 4
Focus the next terminal. This is an alias for \fBgo_next\fP.
.br
Default value: \fB<Ctrl>Tab\fP
.RE
.sp
\fBcycle_prev\fP
.RS 4
Focus the previous terminal. This is an alias for \fBgo_prev\fP.
.br
Default value: \fB<Ctrl><Shift>Tab\fP
.RE
.sp
\fBgo_next\fP
.RS 4
Focus the next terminal.
.br
Default value: \fB<Ctrl><Shift>N\fP
.RE
.sp
\fBgo_prev\fP
.RS 4
Focus the previous terminal.
.br
Default value: \fB<Ctrl><Shift>P\fP
.RE
.sp
\fBgo_up\fP
.RS 4
Focus the terminal above the current one.
.br
Default value: \fB<Alt>Up\fP
.RE
.sp
\fBgo_down\fP
.RS 4
Focus the terminal below the current one.
.br
Default value: \fB<Alt>Down\fP
.RE
.sp
\fBgo_left\fP
.RS 4
Focus the terminal to the left of the current one.
.br
Default value: \fB<Alt>Left\fP
.RE
.sp
\fBgo_right\fP
.RS 4
Focus the terminal to the right of the current one.
.br
Default value: \fB<Alt>Right\fP
.RE
.sp
\fBpage_up\fP
.RS 4
Scroll the terminal up one page.
.RE
.sp
\fBpage_down\fP
.RS 4
Scroll the terminal down one page.
.RE
.sp
\fBpage_up_half\fP
.RS 4
Scroll the terminal up half a page.
.RE
.sp
\fBpage_down_half\fP
.RS 4
Scroll the terminal down half a page.
.RE
.sp
\fBline_up\fP
.RS 4
Scroll the terminal up one line.
.RE
.sp
\fBline_down\fP
.RS 4
Scroll the terminal down one line.
.RE
.sp
\fBnext_tab\fP
.RS 4
Move to the next tab.
.br
Default value: \fB<Ctrl>Page_Down\fP
.RE
.sp
\fBprev_tab\fP
.RS 4
Move to the previous tab.
.br
Default value: \fB<Ctrl>Page_Up\fP
.RE
.sp
\fBswitch_to_tab_1\fP, \fBswitch_to_tab_2\fP, ... \fBswitch_to_tab_10\fP
.RS 4
Move to the \fBN\fPth tab.
Note that \fB<Alt><Shift>1\fP may be provided as \fB<Alt>!\fP or similar,
depending on the keyboard layout.
.RE
.SS "Organisation"
.sp
\fBresize_up\fP
.RS 4
Move the parent dragbar up.
.br
Default value: \fB<Ctrl><Shift>Up\fP
.RE
.sp
\fBresize_down\fP
.RS 4
Move the parent dragbar down.
.br
Default value: \fB<Ctrl><Shift>Down\fP
.RE
.sp
\fBresize_left\fP
.RS 4
Move the parent dragbar left.
.br
Default value: \fB<Ctrl><Shift>Left\fP
.RE
.sp
\fBresize_right\fP
.RS 4
Move the parent dragbar right.
.br
Default value: \fB<Ctrl><Shift>Right\fP
.RE
.sp
\fBrotate_cw\fP
.RS 4
Rotate terminals clockwise.
.br
Default value: \fB<Super>R\fP
.RE
.sp
\fBrotate_ccw\fP
.RS 4
Rotate terminals counter+clockwise.
.br
Default value: \fB<Super><Shift>R\fP
.RE
.sp
\fBmove_tab_right\fP
.RS 4
Move the current tab to the right by swapping position with the next
tab.
.br
Default value: \fB<Ctrl><Shift>Page_Down\fP
.RE
.sp
\fBmove_tab_left\fP
.RS 4
Move the current tab to the left by swapping position with the previous
tab.
.br
Default value: \fB<Ctrl><Shift>Page_Up\fP
.RE
.SS "Focus"
.sp
\fBfull_screen\fP
.RS 4
Toggle window to fullscreen.
.br
Default value: \fBF11\fP
.RE
.sp
\fBtoggle_zoom\fP
.RS 4
Toggle maximisation of the current terminal.
.br
Default value: \fB<Ctrl><Shift>X\fP
.RE
.sp
\fBscaled_zoom\fP
.RS 4
Toggle maximisation of the current terminal and scale the font when
maximised.
.br
Default value: \fB<Ctrl><Shift>Z\fP
.RE
.sp
\fBhide_window\fP
.RS 4
Hide/Show all Terminator windows.
.br
Default value: \fB<Ctrl><Shift><Alt>A\fP
.RE
.SS "Grouping & Broadcasting"
.sp
\fBcreate_group\fP
.RS 4
Create a new group.
.RE
.sp
\fBgroup_all\fP
.RS 4
Group all terminals together.
.br
Default value: \fB<Super>G\fP
.RE
.sp
\fBungroup_all\fP
.RS 4
Ungroup all terminals.
.RE
.sp
\fBgroup_all_toggle\fP
.RS 4
Toggle grouping of all terminals.
.RE
.sp
\fBgroup_win\fP
.RS 4
Group all terminals in the current window together.
.RE
.sp
\fBungroup_win\fP
.RS 4
Ungroup all terminals in the current window.
.br
Default value: \fB<Super><Shift>W\fP
.RE
.sp
\fBgroup_win_toggle\fP
.RS 4
Toggle grouping of all terminals in the current window.
.RE
.sp
\fBgroup_tab\fP
.RS 4
Group all terminals in the current tab together.
.br
Default value: \fB<Super>T\fP
.RE
.sp
\fBungroup_tab\fP
.RS 4
Ungroup all terminals in the current tab.
.br
Default value: \fB<Super><Shift>T\fP
.RE
.sp
\fBgroup_tab_toggle\fP
.RS 4
Toggle grouping of all terminals in the current tab.
.RE
.sp
\fBbroadcast_off\fP
.RS 4
Turn broadcasting off.
.RE
.sp
\fBbroadcast_group\fP
.RS 4
Broadcast to all terminals in the same group as the current terminal.
.RE
.sp
\fBbroadcast_all\fP
.RS 4
Broadcast to all terminals.
.RE
.SS "Miscellaneous"
.sp
\fBhelp\fP
.RS 4
Open the full HTML manual in the browser.
.br
Default value: \fBF1\fP
.RE
.sp
\fBpreferences\fP
.RS 4
Open the Preferences window.
.RE
.sp
\fBpreferences_keybindings\fP
.RS 4
Open the Preferences window and show the Keybindings tab.
.br
Default value: \fB<Ctrl><Shift>K\fP
.RE
.sp
\fBcopy\fP
.RS 4
Copy the selected text to the Clipboard.
.br
Default value: \fB<Ctrl><Shift>C\fP
.RE
.sp
\fBpaste\fP
.RS 4
Paste the current contents of the Clipboard.
.br
Default value: \fB<Ctrl><Shift>V\fP
.RE
.sp
\fBpaste_selection\fP
.RS 4
Paste the current contents of the Primary Selection.
.RE
.sp
\fBtoggle_scrollbar\fP
.RS 4
Toggle the scrollbar.
.br
Default value: \fB<Ctrl><Shift>S\fP
.RE
.sp
\fBsearch\fP
.RS 4
Search for text in the terminal scrollback history.
.br
Default value: \fB<Ctrl><Shift>F\fP
.RE
.sp
\fBreset\fP
.RS 4
Reset the terminal state.
.br
Default value: \fB<Ctrl><Shift>R\fP
.RE
.sp
\fBreset_clear\fP
.RS 4
Reset the terminal state and clear the terminal window.
.br
Default value: \fB<Ctrl><Shift>G\fP
.RE
.sp
\fBzoom_in\fP
.RS 4
Increase the font size by one unit.
.br
Default value: \fB<Ctrl>plus\fP
.RE
.sp
\fBzoom_out\fP
.RS 4
Decrease the font size by one unit.
.br
Default value: \fB<Ctrl>minus\fP
.RE
.sp
\fBzoom_normal\fP
.RS 4
Restore the original font size.
.br
Default value: \fB<Ctrl>0\fP
.RE
.sp
\fBzoom_in_all\fP
.RS 4
Increase the font size by one unit for all terminals.
.RE
.sp
\fBzoom_out_all\fP
.RS 4
Decrease the font size by one unit for all terminals.
.RE
.sp
\fBzoom_normal_all\fP
.RS 4
Restore the original font size for all terminals.
.RE
.sp
\fBedit_window_title\fP
.RS 4
Rename the current window.
.br
Default value: \fB<Ctrl><Alt>W\fP
.RE
.sp
\fBedit_tab_title\fP
.RS 4
Rename the current tab.
.br
Default value: \fB<Ctrl><Alt>A\fP
.RE
.sp
\fBedit_terminal_title\fP
.RS 4
Rename the current terminal.
.br
Default value: \fB<Ctrl><Alt>X\fP
.RE
.sp
\fBinsert_number\fP
.RS 4
Insert the current terminal\(cqs number, i.e. 1 to 12.
.br
Default value: \fB<Super>1\fP
.RE
.sp
\fBinsert_padded\fP
.RS 4
Insert the current terminal\(cqs number, but zero padded, i.e. 01 to 12.
.br
Default value: \fB<Super>0\fP
.RE
.sp
\fBnext_profile\fP
.RS 4
Switch to the next profile.
.RE
.sp
\fBprevious_profile\fP
.RS 4
Switch to the previous profile.
.RE
.SH "PROFILES"
.sp
These are the options Terminator currently supports in the \fBprofiles\fP
section. Each profile should be its own subsection with a header in the
format \fB[[name]]\fP.
.SS "General"
.sp
\fBallow_bold\fP = \fIboolean\fP
.RS 4
If set to True, text in the terminal can displayed in bold.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBcopy_on_selection\fP = \fIboolean\fP
.RS 4
If set to True, text selections will be automatically copied to the
Clipboard, in addition to being copied to the Primary Selection.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBdisable_mousewheel_zoom\fP = \fIboolean\fP
.RS 4
If set to True, Ctrl+mouse_wheel will not zoom or unzoom the terminal.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBword_chars\fP = \fIstring\fP
.RS 4
Specify the characters that will be considered part of a single word
when selecting text by word.
Hyphen and alphanumerics do not need to be specified.
Ranges can be given, e.g. "A\-Z".
.br
For example, if \fBword_chars\fP = "," then "foo,bar" is considered a single
word.
.br
Default value: \fB\-,./?%&#:_\fP
.RE
.sp
\fBmouse_autohide\fP = \fIboolean\fP
.RS 4
If set to True, the mouse pointer will be hidden when typing.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBterm\fP = \fIstring\fP
.RS 4
Specify the value Terminator will assign to the \*(AqTERM\*(Aq environment
variable.
.br
Default value: \fBxterm\-256color\fP
.RE
.sp
\fBcolorterm\fP = \fIstring\fP
.RS 4
Specify the value Terminator will assign to the \*(AqCOLORTERM\*(Aq environment
variable.
.br
Default value: \fBtruecolor\fP
.RE
.sp
\fBsplit_to_group\fP = \fIboolean\fP
.RS 4
If set to True, the terminal created by splitting will be inserted in
the current terminal\(cqs group.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBautoclean_groups\fP = \fIboolean\fP
.RS 4
If set to True, empty groups will be removed.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBuse_system_font\fP = \fIboolean\fP
.RS 4
If set to True, the system default font will be used for text in the
terminal. Otherwise, the value of \fBfont\fP will be used.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBfont\fP = \fIstring\fP
.RS 4
Specify which font to use for text in the terminal.
This option is ignored unless \fBuse_system_font\fP is set to False.
.br
Default value: \fBMono 10\fP
.RE
.sp
\fBcursor_blink\fP = \fIboolean\fP
.RS 4
If set to True, the cursor will blink when not typing.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBcursor_shape\fP = \fIstring\fP
.RS 4
Specify the shape of the cursor.
Can be any of: \*(Aqblock\*(Aq, \*(Aqunderline\*(Aq, \*(Aqibeam\*(Aq.
.br
Default value: \fBblock\fP
.RE
.sp
\fBcursor_color_default\fP = \fIboolean\fP
.RS 4
If set to True, the background and foreground colors of the terminal
will be used as foreground and background colors for the cursor,
respectively.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBcursor_fg_color\fP = \fIcolor string\fP
.RS 4
Specify the foreground color to use for the cursor.
This option is ignored unless \fBcursor_color_default\fP is set to False.
.RE
.sp
\fBcursor_bg_color\fP = \fIcolor string\fP
.RS 4
Specify the background color to use for the cursor.
This option is ignored unless \fBcursor_color_default\fP is set to False.
.RE
.sp
\fBaudible_bell\fP = \fIboolean\fP
.RS 4
If set to True, a sound will be played when an application writes the
escape sequence for the terminal bell.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBvisible_bell\fP = \fIboolean\fP
.RS 4
If set to True, the terminal will flash when an application writes the
escape sequence for the terminal bell.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBurgent_bell\fP = \fIboolean\fP
.RS 4
If set to True, the window\(cqs urgency hint will be set when an
application writes the escape sequence for the terminal bell.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBicon_bell\fP = \fIboolean\fP
.RS 4
If set to True, a small icon will be shown on the terminal titlebar when
an application writes the escape sequence for the terminal bell.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBforce_no_bell\fP = \fIboolean\fP
.RS 4
If set to True, the terminal bell will be completely disabled.
.br
Default value: \fBFalse\fP
.RE
.SS "Command"
.sp
\fBlogin_shell\fP = \fIboolean\fP
.RS 4
If set to True, the terminal will run the default shell (or the command
specified by \fBcustom_command\fP) as a login shell.
This means the first argument passed to the shell/command will be \*(Aq\-l\*(Aq.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBuse_custom_command\fP = \fIboolean\fP
.RS 4
If set to True, the value of \fBcustom_command\fP will be used instead of
the default shell.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBcustom_command\fP = \fIstring\fP
.RS 4
Specify the command to execute instead of the default shell.
This option is ignored unless \fBuse_custom_command\fP is set to True.
.RE
.sp
\fBexit_action\fP = \fIstring\fP
.RS 4
Specify the action to perform when the terminal is closed.
\*(Aqclose\*(Aq to remove the terminal.
\*(Aqrestart\*(Aq to restart the shell (or the command specified by
\fBcustom_command\fP).
\*(Aqhold\*(Aq to keep the terminal open, even if the process in it has
terminated.
.br
Default value: \fBclose\fP
.RE
.SS "Colors"
.sp
\fBuse_theme_colors\fP = \fIboolean\fP
.RS 4
If set to True, the theme\(cqs foreground and background colors will be
used for the terminal. Otherwise, the values of \fBforeground_color\fP and
\fBbackground_color\fP will be used.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBforeground_color\fP = \fIcolor string\fP
.RS 4
Specify the foreground color to use for the terminal.
This option is ignored unless \fBuse_theme_colors\fP is set to False.
.br
Default value: \fB#AAAAAA\fP
.RE
.sp
\fBbackground_color\fP = \fIcolor string\fP
.RS 4
Specify the background color to use for the terminal.
This option is ignored unless \fBuse_theme_colors\fP is set to False.
.br
Default value: \fB#000000\fP
.RE
.sp
\fBpalette\fP = \fIstring list of colors\fP
.RS 4
Specify the 16\-color palette to use for the terminal.
The value must be a string containing a colon\-separated list of colors
in hex format.
.br
For example, "#000000:#cd0000:#00cd00: ... ".
.RE
.sp
\fBbold_is_bright\fP = \fIboolean\fP
.RS 4
If set to True, bold text will have brighter colors.
.br
Default value: \fBFalse\fP
.RE
.SS "Background"
.sp
\fBbackground_darkness\fP = \fIfloat\fP
.RS 4
Specify the transparency of the background color.
The value must be between 0.0 and 1.0.
This option is ignored unless \fBbackground_type\fP is set to \*(Aqtransparent\*(Aq
or \*(Aqimage\*(Aq.
.br
Default value: \fB0.5\fP
.RE
.sp
\fBbackground_type\fP = \fIstring\fP
.RS 4
Specify what type of background the terminal will have.
\*(Aqsolid\*(Aq for a solid (opaque) background.
\*(Aqtransparent\*(Aq for a transparent background.
\*(Aqimage\*(Aq for a background image.
.br
If this is set to \*(Aqtransparent\*(Aq, the transparency of the background will
be the value of \fBbackground_darkness\fP.
If this is set to \*(Aqimage\*(Aq, the image specified by \fBbackground_image\fP
will be the background; the background color will then be drawn on top
of it, with a transparency specified by \fBbackground_darkness\fP.
.br
Default value: \fBsolid\fP
.RE
.sp
\fBbackground_image\fP = \fIpath string\fP
.RS 4
Specify the path to an image that will be used as background.
This option is ignored unless \fBbackground_type\fP is set to \*(Aqimage\*(Aq.
.RE
.sp
\fBbackground_image_mode\fP = \fIstring\fP
.RS 4
Specify how the background image will be drawn.
\*(Aqstretch_and_fill\*(Aq to fill the terminal entirely, without necessarily
maintaining aspect ratio.
\*(Aqscale_and_fit\*(Aq to fit the image inside the terminal, eventually leaving
blank bars, while maintaining aspect ratio.
\*(Aqscale_and_crop\*(Aq to fill the terminal entirely, eventually cropping the
image, while maintaining aspect ratio.
\*(Aqtiling\*(Aq to repeat the image as to fill the terminal.
This option is ignored unless \fBbackground_type\fP is set to \*(Aqimage\*(Aq.
.br
Default value: \fBstretch_and_fill\fP
.RE
.sp
\fBbackground_image_align_horiz\fP = \fIstring\fP
.RS 4
Specify the horizontal alignment of the background image.
Can be any of: \*(Aqleft\*(Aq, \*(Aqcenter\*(Aq, \*(Aqright\*(Aq.
This option is ignored unless \fBbackground_type\fP is set to \*(Aqimage\*(Aq.
.br
Default value: \fBcenter\fP
.RE
.sp
\fBbackground_image_align_vert\fP = \fIstring\fP
.RS 4
Specify the vertical alignment of the background image.
Can be any of: \*(Aqtop\*(Aq, \*(Aqmiddle\*(Aq, \*(Aqbottom\*(Aq.
This option is ignored unless \fBbackground_type\fP is set to \*(Aqimage\*(Aq.
.br
Default value: \fBmiddle\fP
.RE
.SS "Scrolling"
.sp
\fBscrollbar_position\fP = \fIstring\fP
.RS 4
Specify where the terminal scrollbar is put.
Can be any of: \*(Aqleft\*(Aq, \*(Aqright\*(Aq, \*(Aqhidden\*(Aq.
.br
Default value: \fBright\fP
.RE
.sp
\fBscroll_on_output\fP = \fIboolean\fP
.RS 4
If set to True, the terminall will scroll to the bottom when an
application writes text to it.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBscroll_on_keystroke\fP = \fIboolean\fP
.RS 4
If set to True, the terminal will scroll to the bottom when typing.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBscrollback_infinite\fP = \fIboolean\fP
.RS 4
If set to True, the terminal will keep the entire scrollback history.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBscrollback_lines\fP = \fIinteger\fP
.RS 4
Specify how many lines of scrollback history will be kept by the
terminal. Lines that don\(cqt fit in the scrollback history will be
discarted. Note that setting large values can slow down rewrapping and
resizing.
This option is ignored unless \fBscrollback_infinite\fP is set to False.
.br
Default value: \fB500\fP
.RE
.SS "Compatibility"
.sp
\fBbackspace_binding\fP = \fIstring\fP
.RS 4
Specify what code will be generated by the backspace key.
The value can be:
\*(Aqascii\-del\*(Aq for the ASCII DEL character;
\*(Aqcontrol\-h\*(Aq for the ASCII BS character (Ctrl+H);
\*(Aqescape\-sequence\*(Aq for the escape sequence typically bound to backspace
or delete;
\*(Aqautomatic\*(Aq for letting the terminal automatically decide the character
sequence to use.
.br
Default value: \fBascii\-del\fP
.RE
.sp
\fBdelete_binding\fP = \fIstring\fP
.RS 4
Specify what code will be generated by the delete key.
The value can be:
\*(Aqascii\-del\*(Aq for the ASCII DEL character;
\*(Aqcontrol\-h\*(Aq for the ASCII BS character (Ctrl+H);
\*(Aqescape\-sequence\*(Aq for the escape sequence typically bound to backspace
or delete;
\*(Aqautomatic\*(Aq for letting the terminal automatically decide the character
sequence to use.
.br
Default value: \fBescape\-sequence\fP
.RE
.SS "Titlebar"
.sp
\fBshow_titlebar\fP = \fIboolean\fP
.RS 4
If set to True, the terminal will have a titlebar showing the current
title of that terminal.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBtitle_hide_sizetext\fP = \fIboolean\fP
.RS 4
If set to True, the size of the terminal will not be written on its
titlebar.
.br
Default value: \fBFalse\fP
.RE
.sp
\fBtitle_use_system_font\fP = \fIboolean\fP
.RS 4
If set to True, the system default font will be used for text in the
terminal\(cqs titlebar. Otherwise, the value of \fBtitle_font\fP will be used.
.br
Default value: \fBTrue\fP
.RE
.sp
\fBtitle_font\fP = \fIstring\fP
.RS 4
Specify which font to use for text in the terminal\(cqs titlebar.
This option is ignored unless \fBtitle_use_system_font\fP is set to False.
.br
Default value: \fBSans 9\fP
.RE
.sp
\fBtitle_transmit_fg_color\fP = \fIcolor string\fP
.RS 4
Specify the foreground color to use for the terminal\(cqs titlebar in case
the terminal is focused.
.br
Default value: \fB#ffffff\fP
.RE
.sp
\fBtitle_transmit_bg_color\fP = \fIcolor string\fP
.RS 4
Specify the background color to use for the terminal\(cqs titlebar in case
the terminal is focused.
.br
Default value: \fB#c80003\fP
.RE
.sp
\fBtitle_inactive_fg_color\fP = \fIcolor string\fP
.RS 4
Specify the foreground color to use for the terminal\(cqs titlebar in case
the terminal is unfocused.
.br
Default value: \fB#000000\fP
.RE
.sp
\fBtitle_inactive_bg_color\fP = \fIcolor string\fP
.RS 4
Specify the background color to use for the terminal\(cqs titlebar in case
the terminal is unfocused.
.br
Default value: \fB#c0bebf\fP
.RE
.sp
\fBtitle_receive_fg_color\fP = \fIcolor string\fP
.RS 4
Specify the foreground color to use for the terminal\(cqs titlebar in case
the terminal is in a group and is receiving input while unfocused.
.br
Default value: \fB#ffffff\fP
.RE
.sp
\fBtitle_receive_bg_color\fP = \fIcolor string\fP
.RS 4
Specify the background color to use for the terminal\(cqs titlebar in case
the terminal is in a group and is receiving input while unfocused.
.br
Default value: \fB#0076c9\fP
.RE
.SH "LAYOUTS"
.sp
The \fBlayouts\fP section contains all the saved layouts. Each layout should
be its own subsection with a header in the format \fB[[name]]\fP.
.sp
Each object in a layout is a named sub\-sub\-section with various
properties.
.sp
\fBtype\fP = \fIstring\fP
.RS 4
Can be any of: \*(AqWindow\*(Aq, \*(AqNotebook\*(Aq, \*(AqHPaned\*(Aq, \*(AqVPaned\*(Aq, \*(AqTerminal\*(Aq.
.RE
.sp
\fBparent\fP = \fIstring\fP
.RS 4
Specify which object is the parent of the component being defined.
All objects, except those of type Window, must specify a parent.
.RE
.sp
This is an example of a \fBlayouts\fP section containing only the layout
named "default".
.sp
.if n .RS 4
.nf
.fam C
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
.fam
.fi
.if n .RE
.SH "PLUGINS"
.sp
Terminator plugins can add their own configuration to the config file,
and it will appear as a subsection. Please refer to the documentation of
individual plugins for more information.
.SH "SEE ALSO"
.sp
\fBterminator\fP(1), \c
.URL "https://configobj.readthedocs.io/" "" ""